### ISSUE TITLE
Why not nuxt?

### ISSUE THREAD

**Issue by mgrandl** [chasegiunta/craft-vue#12]
Just a question, but why are we not using nuxt for server side rendering and then just doing the entire templating with vue/nuxt? Would be even more convenient (even though this is already really cool!)

https://familiar.studio/blog/how-we-built-a-large-scale-application-system-using-craft-cms-salesforce-vue-and-nuxt

**Comment by chasegiunta** [comment]
There's nothing to say you couldn't run Craft headless. There's no need for this boilerplate then. But I'd wager that for more Craft sites, a whole vue/nuxt app is overkill. I'm not personally interested in adding another abstraction on top of Vue or Webpack. This template is for those who want a convenient dev environment for implementing vue components with all the benefits of Vue CLI (single config API on top of webpack 4, HMR, compilation, minification) while still getting all the benefits of twig templating (SSR pages without complex building requirements, access to twig's, Craft's, and plugin's filters & twig helpers).
