### ISSUE TITLE
Organizing components in subdirectories?

### ISSUE THREAD

**Issue by swthate** [chasegiunta/craft-vue#13]
This is likely an issue of my own ignorance more than anything else. But is there a way to organize your components into subdirectories?

I want to move `ComponentA.vue` from `src/components` to `src/components/group-a`. But when I do that I end up with Vue warnings like `Invalid component name: "group-a/ComponentA"` and `Unknown custom element: <component-a>`. 

Does the current system of auto-loading components allow subdirectories like this?

**Comment by chasegiunta** [comment]
@swthate I don't believe so. Since the Global autoloading is a Vue approach from the docs, you might be able to search around and see if there's a solution out there for this.

**Comment by swthate** [comment]
I feel like it _should_ be working. I did come across this answer: https://stackoverflow.com/questions/53676837/registering-components-globally-in-vuejs-in-subfolders

The only difference in that `components.js` example is his `componentName` value. It looks like he splits the `fileName` on any `/` character, pops the last value (filename) and strips the `.vue` extension. So the component name should simply be `ComponentName` if its file path is `./components/somesubdirectory/ComponentName.vue`. But my console still says `Invalid component name: "somesubdirectory/ComponentName".`

Everything seems like it should work, but I'll keep looking around here and there when I have time on this.

**Comment by chasegiunta** [comment]
@swthate This is what I'm using... Nearly identical to https://vuejs.org/v2/guide/components-registration.html#Automatic-Global-Registration-of-Base-Components

I'm able to reference components in subdirectories by their name.

```
import Vue from 'vue'
import upperFirst from 'lodash/upperFirst'
import camelCase from 'lodash/camelCase'

const requireComponent = require.context(
  // The relative path of the components folder
  './components',
  // Whether or not to look in subfolders
  true,
  // The regular expression used to match base component filenames
  /[A-Z]\w+\.(vue|js)$/,
)

requireComponent.keys().forEach(fileName => {
  // Get component config
  const componentConfig = requireComponent(fileName)

  // Get PascalCase name of component
  const componentName = upperFirst(
    camelCase(
      // Gets the file name regardless of folder depth
      fileName
        .split('/')
        .pop()
        .replace(/\.\w+$/, ''),
    ),
  )

  // Register component globally
  Vue.component(
    componentName,
    // Look for the component options on `.default`, which will
    // exist if the component was exported with `export default`,
    // otherwise fall back to module's root.
    componentConfig.default || componentConfig,
  )

})
```

**Comment by swthate** [comment]
Oh, awesome, thanks @chasegiunta! I think my problem was I just wasn't using `lodash`... oops!
