### ISSUE TITLE
Handling Prerendering

### ISSUE THREAD

**Issue by Michael-Reich** [chasegiunta/craft-vue#17]
We currently consider this approach for one of our projects. So one question I have is how I could fix the prerendering problem. 

Currently the routes are managed by craft. I tried to use [Vue Prerender](https://github.com/SolarLiner/vue-cli-plugin-prerender-spa) as a framework to prerender vue components, but the problem is, that there is no vue router right?

Would be great to hear youre opinion on this.

**Comment by chasegiunta** [comment]
@Michael-Reich I haven't dealt with pre-rendering with this yet. Typically anything vital that I want to be dynamic & crawlable I put into slots - but you shouldn't feel the need to place all your content within components.

**Comment by chasegiunta** [comment]
Closing for now. Feel free to follow up if you did any more digging

**Comment by Michael-Reich** [comment]
GoodWork Page is built with this setup right? Because if I view Source code there is the whole HTML structure, so SEO is perfectly working right? How did you achieve this, by using vue and craft? 

TY!

**Comment by chasegiunta** [comment]
@Michael-Reich Yes, the Good Work site is built using this same setup, but it's not an SPA. This setup is essentially mounting the entire `body` on every page load, and giving you globally registered components out of the box. Routing is being done through Craft.
