### ISSUE TITLE
ie11 script 1003 error

### ISSUE THREAD

**Issue by puck3000** [chasegiunta/craft-vue#18]
I obviously cannot get babel/webpack to correctly polyfill my vue-components: 

live url:
http://schafeziegen.daniellerch.ch/

git repo:
https://github.com/puck3000/ie11test

Ie11 Console shows script 1003 error (among others) and instead of my components there is a blank space…
any help would be greatly appreciated!

**Comment by chasegiunta** [comment]
@puck3000 first step would be to include a babel.config.js file in the root of your project.

https://github.com/chasegiunta/craft-vue/blob/master/babel.config.js

**Comment by puck3000** [comment]
thank you for your time! 

i tried it… but still no success:

http://ietest.daniellerch.ch/
https://github.com/puck3000/ietest

ist there a second step? 
thank you so much

**Comment by chasegiunta** [comment]
@puck3000 It's a bit hard for me to troubleshoot personally as I don't have a way to test IE 11 on my Mac here, but I can suggest some tips. This has nothing to do with this template specifically, but how to interface with Vue CLI & it's interface of webpack.

- Very first step would be to ensure that _something_ is happening with Babel - that it's actually doing it's thing. Look at the build sizes before & after adding that bable.config.js file.

- If it's a specific polyfill needed, the goal is to figure out which one to enable. A couple of the most common are commented out - might as well uncomment lines 8-13 here, save, and build to see if it has any effect. https://github.com/puck3000/ietest/blob/f0249a0f4de9e3a375972ebce3a61189ea972bf3/babel.config.js#L9

- If you can look at IE11 while your development is running, figure out which file has the incompatible code through sourcemaps. If you only have access to your production build through IE11, enable sourcemaps in your production build (https://cli.vuejs.org/config/#productionsourcemap) . It may be that one of your dependencies needs to be transpiled and you'll have to reference it through this option in your vue.config.js https://cli.vuejs.org/config/#transpiledependencies

**Comment by puck3000** [comment]
thank you again so much for your time. 
i am struggling with debugging on my mac too, i’m testing with https://lambdatest.com <https://www.lambdatest.com/> – for free at the moment. 
I did as you suggested, and yes, babel is doing something (legacy build increases with babel.config.js).  I added the polyfills in babel.config but obviously ie11 is still having problems with stuff like

data() {}

notation… doesn’t seem like a dependency but a vue basic problem… 

again, im very greatful  for your help and if you have a patreon account or similar, please let me know, i would love to offer you a beer (or 10). 

Thank you, best regards
Daniel

**Comment by chasegiunta** [comment]
Hmm... Did you try those other two steps I mentioned? Can you update the repo if you did? I can try to take a look better this evening. And I'll take any beer money I can get! paypal.me/ChaseGiunta or https://beerpay.io/chasegiunta/craft-vue

**Comment by puck3000** [comment]
Hy again

Sorry for not responding yesterday, it was a really busy day. But now I’m back at it:

I’m still stuck with my ie11 problem AND i absolutely need to solve it until Friday 12h (European Time) … 
I was thinking about hiring someone on Codementor, but I’d like it much better to give some money to you – if you have time to help. Would 100$ be ok? 

I tried to fix it by enabling the two polyfills that were commented out originally, but it had no effect. If I follow the error in IE11s console, it shows me that it is not able to understand

data() {}
 
notation in my vue component. 

Here’s my updated repo:

https://github.com/puck3000/ietest <https://github.com/puck3000/ietest>

and here the link to the live version:

http://ietest.daniellerch.ch/ <http://ietest.daniellerch.ch/>

and a ie11 screenshot:



 
Please let me know if you have time to troubleshoot this thing with me – thank you very much in advance! (Beermoney  is on your way anyways)

Best regards
daniel

**Comment by puck3000** [comment]
Hy again

I’m very glad to tell you, that after some (many) test, I made a first progress. I think I can handle it from here by myself. Thank you anyways and enjoy your beer! 

Best regards 
Daniel


ps When I’m done I could post the solution in the issue… if you think it might help anyone.

**Comment by chasegiunta** [comment]
@puck3000 Glad to hear! I'm going to go ahead and close this, but please post your solution when you get the chance.
