### ISSUE TITLE
not working with valet

### ISSUE THREAD

**Issue by angrotheman** [chasegiunta/craft-vue#20]
if i install it via composer and link it with valet it does not work.
I have tried it already with MAMP – it was working perfectly!

Vue is not loading – means: Output of index .twig is <hello-world…

Would be great if it is possible to work with it via valet!

**Comment by chasegiunta** [comment]
@angrotheman definitely works with Valet! That's what I use for all my projects, and even all reproductions for this repo.

**Comment by angrotheman** [comment]
do you do something special? or just install it?

**Comment by chasegiunta** [comment]
Nothing special. 

if you're running `yarn dev` or `npm run dev` your css files won't be output

**Comment by angrotheman** [comment]
think i have it.
Safari don't load the app.js because it is not https. Tried it in Chrome and there is everything perfect.

**Comment by chasegiunta** [comment]
@angrotheman Yeah if you're securing your valet install, you may want to set the `https` option in your vue.config.js file to `true` and also set https://github.com/chasegiunta/craft-vue/blob/e541df8cf1032e3b4d42bdb0a9490b14ea28130e/config/twigpack.php#L22
to reflect https

**Comment by angrotheman** [comment]
thanks for your fast help, I think it is working now! Your repo is really great to start with vue & craft

**Comment by chasegiunta** [comment]
No problem! Glad you're up & running.

**Comment by aquafun** [comment]
> @angrotheman Yeah if you're securing your valet install, you may want to set the `https` option in your vue.config.js file to `true` and also set
> 
> https://github.com/chasegiunta/craft-vue/blob/e541df8cf1032e3b4d42bdb0a9490b14ea28130e/config/twigpack.php#L22
> 
> 
> to reflect https

sorry… I try now hours but I don't get it work…
chrome want to load socks-node/info from HTTPS://localhost

but my localhost is not secured. can I changed it? if I set https to true it will load anything with https

**Comment by angrotheman** [comment]
> @angrotheman Yeah if you're securing your valet install, you may want to set the `https` option in your vue.config.js file to `true` and also set
> 
> https://github.com/chasegiunta/craft-vue/blob/e541df8cf1032e3b4d42bdb0a9490b14ea28130e/config/twigpack.php#L22
> 
> 
> to reflect https

sorry… I try now hours but I don't get it work…
chrome want to load socks-node/info from HTTPS://localhost

but my localhost is not secured. can I changed it? if I set https to true it will try to load anything from https
