### ISSUE TITLE
css files handling

### ISSUE THREAD

**Issue by angrotheman** [chasegiunta/craft-vue#22]
i think I'm just doing something wrong.
But how can i add new css files?
if i use `npm run dev` and import a css file in the main.js everything works as expected but if i run `npm run build` the css file is not loading. It's just loading the app.css file from the src folder and my custom css from my component combined to one file. How can i add my file which i import?

**Comment by chasegiunta** [comment]
@angrotheman If you're importing your css file into your `main.js` file it should be compiling that all down into your final `app.css`. I may need some more context to troubleshoot.

**Comment by angrotheman** [comment]
yep i thought this too but it doesn't work…

**main.js:**
`import 'mystylefile.css';`

**run** npm run dev 
loads correctly.

**run** npm run build
everything gets compiled into the final app.css except my` mystylefile.css`.

**Comment by chasegiunta** [comment]
I tested locally when you opened this issue with the same setup and it worked correctly, so not sure what could be going on. You're not running a post-processor like PurgeCSS are you?

You could also try doing an `@import` in your css file that _is_ compiling, but that's just a workaround.

**Comment by angrotheman** [comment]
i think some classes of my css are not included… 

crazy thing…

**Comment by chasegiunta** [comment]
@angrotheman can you send me the project?

**Comment by chasegiunta** [comment]
@angrotheman Also, try clearing your twigpack cache in Utilities -> Clear Caches section of the CP

**Comment by angrotheman** [comment]
I have tried it but i think this was a problem with a npm package.
But now even on a fresh craft-vue installation, if i run `npm run build` my page load no css or js. So vue only works on `npm run dev`
