### ISSUE TITLE
Update for craft 4

### ISSUE THREAD

**Issue by stillhartkonzept** [chasegiunta/craft-vue#42]
Hi! Does anyone know if there's a roadmap for updating this repo to work with craft 4 and/or php 8? Our host is changing to php 8, and this breaks a site we have running using this.

**Comment by chasegiunta** [comment]
@stillhartkonzept I have no plans on updating it. I may, in the future, create a Craft 4 / PHP 8 / Vue & Vite starter, but at this point, I have no plans on continuing with Vue CLI.
