### ISSUE TITLE
Not an issue, looking for infos !

### ISSUE THREAD

**Issue by felixdenoix** [chasegiunta/craft-vue#6]
Hello !
I just installed your boilerplate and looks really nice. 👌🏻 
Nonetheless I was wondering if you had more information to provide on the way you are using this boilerplate (mostly about the way you are handling page transition and the way you are passing data into vue components) ?
Thanks in advance

**Comment by chasegiunta** [comment]
@felixdenoix This boilerplate doesn't handle page transitions. Theoretically you could use vue-router and handle page transitions like normal, but you'd lose the benefit of twig & Craft's routing. 

This boilerplate simply mounts the Vue instance to your base layout, and allows you to use Vue's single file components easily throughout your pages - giving you some nice development features and production bundling as well.

**Comment by felixdenoix** [comment]
Thanks for the quick reply @chasegiunta !
